# Run when we create a new release/tag
---
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

name: Release process

env:
  SOURCE_DIR: ./
  ARTIFACTS_DIR: debian/build/release/

jobs:
  create-deb:
    name: Create deb
    runs-on: ubuntu-latest
    outputs:
      release-id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: source
      - name: Enable source repositories
        run: sudo sed -i 's/^# deb-src/deb-src/' /etc/apt/sources.list
      - name: DUmp
        run: cat /etc/apt/sources.list; ls /etc/apt/sources.list.d/; cat /etc/apt/sources.list.d/*
      - name: Install needed packages
        run: |
            sudo apt-get update
            sudo apt-get install -y devscripts equivs git-buildpackage build-essential
        env:
          DEBIAN_FRONTEND: "noninteractive"
      - name: Install build packages
        run: sudo mk-build-deps --install \
               --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' \
               debian/control
        working-directory: source
        env:
          DEBIAN_FRONTEND: "noninteractive"
      - name: Dump git information
        run: |
            env
            git branch -v
            git remote -v
            git log --oneline
            echo ${GITHUB_REF}
            echo ${GITHUB_REF##*/}
        working-directory: source
      - name: Update the changelog
        run: |
            set -o allexport
            source /etc/os-release
            gbp dch --release --new-version=${GITHUB_REF##*/} --distribution=$VERSION_CODENAME \
              --spawn-editor=never --git-ignore-branch
        working-directory: source
      - name: Build Debian package
        run: debuild --no-sign
        working-directory: source
      - name: Upload the artifacts
        run: ls -lh

