# Run when we create a new github release
---
on:
  release:
    types: [created]

name: Release process

jobs:
  create-deb:
    name: Create deb
    runs-on: ubuntu-latest
    steps:
      - name: Drop env for debugging
        run: env
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: source
      - name: Enable source repositories
        run: sudo sed -i 's/^# deb-src/deb-src/' /etc/apt/sources.list
      - name: Install pre-build packages
        run: |
            sudo apt-get update
            sudo apt-get install -y devscripts equivs git-buildpackage build-essential
        env:
          DEBIAN_FRONTEND: "noninteractive"
      - name: Install build packages
        run: sudo mk-build-deps --install
               --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes'
               debian/control
        working-directory: source
        env:
          DEBIAN_FRONTEND: "noninteractive"
      - name: Update the changelog
        run: |
            set -o allexport
            source /etc/os-release
            [[ $GITHUB_REF == *tags* ]] && VER_OPT="--new-version=${GITHUB_REF##*/}" #"
            gbp dch --release $VER_OPT --distribution=$VERSION_CODENAME --spawn-editor=never --ignore-branch
        working-directory: source
      - name: Build Debian package
        run: debuild --no-sign
        working-directory: source
      - name: List the artifacts
        run: ls -lh
      - name: Upload the artifacts to the release
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "crtime*"
